version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: "daily"
  open-pull-requests-limit: 10
  groups:
    tests:
      patterns: ["*"]
      update-types: ["minor", "patch"]
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: "daily"
  open-pull-requests-limit: 10
- package-ecosystem: dotnet-sdk
  directory: "/"
  schedule:
    interval: "daily"
  open-pull-requests-limit: 10
