// <auto-generated />
using System;
using Issue12MySQL.DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Issue12MySQL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("Issue12MySQL.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("AddDate")
                        .HasColumnType("datetime");

                    b.Property<byte[]>("ByteArrayValue")
                        .HasColumnType("varbinary(4000)");

                    b.Property<byte>("ByteValue")
                        .HasColumnType("tinyint unsigned");

                    b.Property<char>("CharValue")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTimeOffsetValue")
                        .HasColumnType("datetime");

                    b.Property<decimal>("DecimalValue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<double>("DoubleValue")
                        .HasColumnType("double");

                    b.Property<float>("FloatValue")
                        .HasColumnType("float");

                    b.Property<byte[]>("GuidValue")
                        .IsRequired()
                        .HasColumnType("varbinary(16)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long>("Points")
                        .HasColumnType("bigint");

                    b.Property<short>("ShortValue")
                        .HasColumnType("smallint");

                    b.Property<TimeSpan>("TimeSpanValue")
                        .HasColumnType("time");

                    b.Property<uint>("UintValue")
                        .HasColumnType("int unsigned");

                    b.Property<ulong>("UlongValue")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime");

                    b.Property<ulong>("UshortValue")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Id");

                    b.ToTable("People");
                });
#pragma warning restore 612, 618
        }
    }
}
