// <auto-generated />
using System;
using Issue9SQLiteInt32.DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Issue9SQLiteInt32.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200322194455_V2020_03_23_0014")]
    partial class V2020_03_23_0014
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("Issue9SQLiteInt32.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddDate")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ByteArrayValue")
                        .HasColumnType("BLOB");

                    b.Property<byte>("ByteValue")
                        .HasColumnType("INTEGER");

                    b.Property<char>("CharValue")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTimeOffsetValue")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DecimalValue")
                        .HasColumnType("TEXT");

                    b.Property<double>("DoubleValue")
                        .HasColumnType("REAL");

                    b.Property<float>("FloatValue")
                        .HasColumnType("REAL");

                    b.Property<Guid>("GuidValue")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NumericDecimalValue")
                        .HasColumnType("numeric");

                    b.Property<long>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<short>("ShortValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimeSpanValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UintValue")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UlongValue")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("UshortValue")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("People");
                });
#pragma warning restore 612, 618
        }
    }
}
