// <auto-generated />
using System;
using Issue9SQLiteInt32.DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Issue9SQLiteInt32.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251224191625_V2025_12_24_2245")]
    partial class V2025_12_24_2245
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Issue9SQLiteInt32.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddDate")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ByteArrayValue")
                        .HasColumnType("BLOB");

                    b.Property<byte>("ByteValue")
                        .HasColumnType("INTEGER");

                    b.Property<char>("CharValue")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DateTimeOffsetValue")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DecimalValue")
                        .HasColumnType("TEXT");

                    b.Property<double>("DoubleValue")
                        .HasColumnType("REAL");

                    b.Property<float>("FloatValue")
                        .HasColumnType("REAL");

                    b.Property<Guid>("GuidValue")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NumericDecimalValue")
                        .HasColumnType("numeric");

                    b.Property<long>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<short>("ShortValue")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("TimeSpanValue")
                        .HasColumnType("TEXT");

                    b.Property<uint>("UintValue")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("UlongValue")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("UshortValue")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("People");
                });
#pragma warning restore 612, 618
        }
    }
}
